UPDATE Commander
SET
  password = 'sp2024'
  username = CASE
    WHEN id = 3	 THEN	'kumar_sp'
    WHEN id = 4	 THEN	'bikremjit_sp'
    WHEN id = 5	 THEN	'wendi_sp'
    WHEN id = 6	 THEN	'carson_sp'
    WHEN id = 7	 THEN	'santhosh_sp'
    WHEN id = 8	 THEN	'brian_sp'
    WHEN id = 9	 THEN	'royhaan_sp'
    WHEN id = 10 THEN	'oliver_sp'
    WHEN id = 11 THEN	'mark_sp'
    WHEN id = 12 THEN	'shing_sp'
    WHEN id = 13 THEN	'sharma_sp'
    WHEN id = 14 THEN	'nicholas_sp'
    WHEN id = 15 THEN	'yong_sp'
    WHEN id = 16 THEN	'syhamii_sp'
    WHEN id = 17 THEN	'carter_sp'
    WHEN id = 18 THEN	'fahmy_sp'
    WHEN id = 19 THEN	'yi_sp'
    WHEN id = 20 THEN	'chun_sp'
    WHEN id = 21 THEN	'vernon_sp'
    WHEN id = 22 THEN	'melvin_sp'
    WHEN id = 23 THEN	'yan_sp'
    WHEN id = 24 THEN	'hikaru_sp'
    WHEN id = 25 THEN	'yu_sp'
    WHEN id = 26 THEN	'xavier_sp'
    WHEN id = 27 THEN	'sam_sp'
    WHEN id = 28 THEN	'aaron_sp'
    WHEN id = 29 THEN	'darshan_sp'
    WHEN id = 30 THEN	'hanes_sp'
    WHEN id = 31 THEN	'chai_sp'
    WHEN id = 32 THEN	'pravar_sp'
    WHEN id = 33 THEN	'wanghong_sp'
    WHEN id = 34 THEN	'aditya_sp'
    WHEN id = 35 THEN	'joel_sp'
    WHEN id = 36 THEN	'sun_sp'
    WHEN id = 37 THEN	'arthur_sp'
    WHEN id = 38 THEN	'spencer_sp'
    WHEN id = 39 THEN	'dervin_sp'
  END
WHERE id IN (3, 4, 5, 6, 7, 8, )
